options:
  host: 'localhost'
  port: '2000'
  prefix: "^[!！] ?(.*)"
  bots: [ 123456789 ]
  groups: [ 123456789 ]
servers:
  id:
    alias: [alias]
    address: "address"
    port: 25575
    password: "password"